columns:
  age :        int
  sex :        object
  bmi :        float
  children:    int
  smoker:      int
  region:      object
  charges:     float



numerical_columns:
  - age
  - bmi
  - children
  - smoker
  - charges 





categorical_columns:
  - sex
  - region




target_column : 
  - charges



  



