columns:
  age :        int
  sex_male :   int
  bmi :        float
  children:    int
  smoker_yes:  int
  region_northwest:  int
  region_southeast : int
  region_southwest : int

  charges:     float



numerical_columns:
  - age
  - bmi
  - children
  - sex_male
  - smoker_yes
  - region_northwest
  - region_southeast
  - region_southwest

  





# categorical_columns:
#   - sex
#   - region
#   - smoker




target_column : 
  - charges






  



